
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gpigkszxnzqqjahykwrm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdwaWdrc3p4bnpxcWphaHlrd3JtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4MDk2NDMsImV4cCI6MjA2MzM4NTY0M30.LyV9h2PAACuh6mTtc0dr7prqZHK927x8bTlyGd6JPhg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
